-- MySQL Script generated by MySQL Workbench
-- Mon Dec  5 16:18:11 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categorias` (
  `idcategorias` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `categorias` VARCHAR(45) NULL,
  PRIMARY KEY (`idcategorias`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`detalle_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`detalle_producto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`productos` (
  `idproductos` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `precio` DECIMAL NULL,
  `detalle_producto_id` INT NOT NULL,
  PRIMARY KEY (`idproductos`),
  INDEX `fk_productos_detalle_producto1_idx` (`detalle_producto_id` ASC) VISIBLE,
  CONSTRAINT `fk_productos_detalle_producto1`
    FOREIGN KEY (`detalle_producto_id`)
    REFERENCES `mydb`.`detalle_producto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`productos_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`productos_categoria` (
  `productos_idproductos` INT NOT NULL,
  `categorias_idcategorias` INT UNSIGNED NOT NULL,
  INDEX `fk_productos_categoria_productos_idx` (`productos_idproductos` ASC) VISIBLE,
  INDEX `fk_productos_categoria_categorias1_idx` (`categorias_idcategorias` ASC) VISIBLE,
  CONSTRAINT `fk_productos_categoria_productos`
    FOREIGN KEY (`productos_idproductos`)
    REFERENCES `mydb`.`productos` (`idproductos`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_productos_categoria_categorias1`
    FOREIGN KEY (`categorias_idcategorias`)
    REFERENCES `mydb`.`categorias` (`idcategorias`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SistemasPagos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SistemasPagos` (
  `idSistemasPagos` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idSistemasPagos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`LugarOrden`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`LugarOrden` (
  `idLugarOrden` INT NOT NULL AUTO_INCREMENT,
  `ciudad` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  `CP` VARCHAR(45) NULL,
  PRIMARY KEY (`idLugarOrden`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Orden`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Orden` (
  `idOrden` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Usuario` VARCHAR(45) NULL,
  `Fecha` DATE NULL,
  `productos_idproductos` INT NOT NULL,
  `SistemasPagos_idSistemasPagos` INT NOT NULL,
  `LugarOrden_idLugarOrden` INT NOT NULL,
  PRIMARY KEY (`idOrden`),
  INDEX `fk_Orden_productos1_idx` (`productos_idproductos` ASC) VISIBLE,
  INDEX `fk_Orden_SistemasPagos1_idx` (`SistemasPagos_idSistemasPagos` ASC) VISIBLE,
  INDEX `fk_Orden_LugarOrden1_idx` (`LugarOrden_idLugarOrden` ASC) VISIBLE,
  CONSTRAINT `fk_Orden_productos1`
    FOREIGN KEY (`productos_idproductos`)
    REFERENCES `mydb`.`productos` (`idproductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Orden_SistemasPagos1`
    FOREIGN KEY (`SistemasPagos_idSistemasPagos`)
    REFERENCES `mydb`.`SistemasPagos` (`idSistemasPagos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Orden_LugarOrden1`
    FOREIGN KEY (`LugarOrden_idLugarOrden`)
    REFERENCES `mydb`.`LugarOrden` (`idLugarOrden`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuarios` (
  `idUsuarios` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `Orden_idOrden` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idUsuarios`),
  INDEX `fk_Usuarios_Orden1_idx` (`Orden_idOrden` ASC) VISIBLE,
  CONSTRAINT `fk_Usuarios_Orden1`
    FOREIGN KEY (`Orden_idOrden`)
    REFERENCES `mydb`.`Orden` (`idOrden`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`perfil` (
  `idperfil` INT NOT NULL,
  `Usuarios_idUsuarios` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idperfil`),
  INDEX `fk_perfil_Usuarios1_idx` (`Usuarios_idUsuarios` ASC) VISIBLE,
  CONSTRAINT `fk_perfil_Usuarios1`
    FOREIGN KEY (`Usuarios_idUsuarios`)
    REFERENCES `mydb`.`Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
