package java01;

public class HolaMundo {
	public static void main(String[] args) {
		String nombre="Ana";
		int numero=5+3;
		System.out.println("Hola Mundo");
		System.out.println("Soy "+nombre);
		//TODO Autogenerated Method Sethup
		char caracter='/';
		String cadena="Hola desde el IDE";
		System.out.println("===>"+caracter);
		System.out.println(cadena);
		System.out.println(numero);
		
	}
}
